// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameDefaultAuth = "default_auth"

// DefaultAuth mapped from table <default_auth>
type DefaultAuth struct {
	ID   int32           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type string          `gorm:"column:type;not null" json:"type"`
	Auth json.RawMessage `gorm:"column:auth;default:json_object()" json:"auth"`
}

// TableName DefaultAuth's table name
func (*DefaultAuth) TableName() string {
	return TableNameDefaultAuth
}
