// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string     `gorm:"column:username;not null" json:"username"`
	Name      *string    `gorm:"column:name" json:"name"`
	Password  string     `gorm:"column:password;not null" json:"password"`
	Birthday  *time.Time `gorm:"column:birthday" json:"birthday"`
	Email     *string    `gorm:"column:email" json:"email"`
	Phone     *string    `gorm:"column:phone" json:"phone"`
	Country   *string    `gorm:"column:country" json:"country"`
	LoginAt   *time.Time `gorm:"column:login_at" json:"login_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CreatedAt *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	WUsers    []WUser    `gorm:"foreignKey:user_id" json:"w_users"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
