// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
	"time"
)

const TableNameWGroup = "w_group"

// WGroup mapped from table <w_group>
type WGroup struct {
	ID          int32           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string          `gorm:"column:name;not null" json:"name"`
	CreatorID   int32           `gorm:"column:creator_id;not null" json:"creator_id"`
	WorkspaceID int32           `gorm:"column:workspace_id;not null" json:"workspace_id"`
	Enable      bool            `gorm:"column:enable;not null" json:"enable"`
	DefaultAuth json.RawMessage `gorm:"column:default_auth;default:json_object()" json:"default_auth"`
	UpdatedAt   *time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CreatedAt   *time.Time      `gorm:"column:created_at;default:now()" json:"created_at"`
	WUserGroups []WUserGroup    `gorm:"foreignKey:w_group_id" json:"w_user_groups"`
}

// TableName WGroup's table name
func (*WGroup) TableName() string {
	return TableNameWGroup
}
