// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWUserGroup = "w_user_group"

// WUserGroup mapped from table <w_user_group>
type WUserGroup struct {
	WUserID  int32 `gorm:"column:w_user_id;primaryKey" json:"w_user_id"`
	WGroupID int32 `gorm:"column:w_group_id;primaryKey" json:"w_group_id"`
}

// TableName WUserGroup's table name
func (*WUserGroup) TableName() string {
	return TableNameWUserGroup
}
