// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWUser = "w_user"

// WUser mapped from table <w_user>
type WUser struct {
	ID         int32           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID        string          `gorm:"column:uid;not null" json:"uid"`
	Username   *string         `gorm:"column:username" json:"username"`
	Password   *string         `gorm:"column:password" json:"password"`
	Birthday   *time.Time      `gorm:"column:birthday" json:"birthday"`
	Email      *string         `gorm:"column:email" json:"email"`
	Phone      *string         `gorm:"column:phone" json:"phone"`
	Country    *string         `gorm:"column:country" json:"country"`
	CreatedAt  *time.Time      `gorm:"column:created_at;default:now()" json:"created_at"`
	groups     []UserGroup     `gorm:"foreignKey:user_id" json:"groups"`
	workspaces []UserWorkspace `gorm:"foreignKey:user_id" json:"workspaces"`
}

// TableName WUser's table name
func (*WUser) TableName() string {
	return TableNameWUser
}
