// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWorkspace = "workspace"

// Workspace mapped from table <workspace>
type Workspace struct {
	ID           int32           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         *string         `gorm:"column:name" json:"name"`
	PreWorkspace *int32          `gorm:"column:pre_workspace" json:"pre_workspace"`
	Rank         int32           `gorm:"column:rank;not null" json:"rank"`
	Ancient      string          `gorm:"column:ancient;not null" json:"ancient"`
	Enable       bool            `gorm:"column:enable;not null" json:"enable"`
	OwnerID      int32           `gorm:"column:owner_id;not null" json:"owner_id"`
	ExpiryDate   time.Time       `gorm:"column:expiry_date;not null" json:"expiry_date"`
	Auth         *string         `gorm:"column:auth;default:json_object()" json:"auth"`
	UserAuth     *string         `gorm:"column:user_auth;default:json_object()" json:"user_auth"`
	CreatedAt    *time.Time      `gorm:"column:created_at;default:now()" json:"created_at"`
	users        []UserWorkspace `gorm:"foreignKey:workspace_id" json:"users"`
	groups       []WGroup        `gorm:"foreignKey:workspace_id" json:"groups"`
}

// TableName Workspace's table name
func (*Workspace) TableName() string {
	return TableNameWorkspace
}
